# Generated by Django 2.2.14 on 2020-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="nhghfhfh",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
