# Generated by Django 2.2.14 on 2020-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_nhghfhfh'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='kjhkjhk',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
