# Generated by Django 2.2.14 on 2020-07-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_customtext_kjhkjhk"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="kjhkjhk",),
        migrations.RemoveField(model_name="customtext", name="nhghfhfh",),
    ]
